### ISSUE TITLE
A Navbar comonent for games

### ISSUE THREAD

**Issue by Navneet-chaurasia** [Navneet-chaurasia/WonderGames#13]
@rockstarCSE057 can you make a navbar component that will apper on games, it will be different from home page navbar
This navbar should consist options for particular to a game

**Comment by rockstarCSE057** [comment]
ok I will try to implement it.

**Comment by Navneet-chaurasia** [comment]
> ok I will try to implement it.

okk nice

**Comment by Navneet-chaurasia** [comment]
All the games will have home navbar at top (primary navbar)
but they will also have secondary navbar below primary navbar
This secondary navbar is specific to that particular game
so it's up to games creator how to create that secondary navbar 

SO I am closing this issue now
